name: Build and Publish .NET Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Restore Dependencies
        run: dotnet restore ApnaBank/ApnaBank/ApnaBank.csproj

      - name: Build Solution
        run: dotnet build ApnaBank/ApnaBank/ApnaBank.csproj --no-restore

      - name: Publish Application
        run: dotnet publish -c Release -o ./app/ ApnaBank/ApnaBank/ApnaBank.csproj

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: app/
